modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="modpackhelper"
version="${file.jarVersion}" #mandatory
displayName="Modpack Helper" #mandatory
logoFile="modpackhelper.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.modpackhelper]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modpackhelper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"